### ISSUE TITLE
How do you run this thing? 

### ISSUE THREAD

**Issue by rhyolight** [TaylorPeer/AI-909#1]
Can you add some instructions to the README, assuming I'm not a native Java developer?

**Comment by TaylorPeer** [comment]
Sure, will get to it tomorrow. Didn't expect anybody to be taking a close look at the code so soon. I also need to add instructions for using the UI, since it probably isn't entirely self-explanatory.

**Comment by rhyolight** [comment]
I love me some musical hacks. Did you see the music theory lesson with @CharlesGillingham from our last hackathon?

[![tGfDjwSORaw](http://img.youtube.com/vi/tGfDjwSORaw/0.jpg)](http://www.youtube.com/watch?v=tGfDjwSORaw)

**Comment by TaylorPeer** [comment]
I had heard about it (some of my coworkers were there) but didn't know there was a video of it online. Thanks for the link!

**Comment by rhyolight** [comment]
Super interesting.

---

Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by TaylorPeer** [comment]
Sorry for the late response - just updated the readme now. Let me know if it's understandable. I also made an explanation video today (https://www.youtube.com/watch?v=GdbqW7E4lvE) but haven't officially submitted it yet since I wanted to get feedback from some people first and might make some changes to it still. Was thinking I should add some more explanation of how it works (how the data is encoded and how new sequences are created).

**Comment by rhyolight** [comment]
Holy crap that's awesome. I'll try to run it today. Looks fun.

**Comment by rhyolight** [comment]
I got it working! REally cool...

**Comment by TaylorPeer** [comment]
Great! Thanks.
